### ISSUE TITLE
Non-interactive use

### ISSUE THREAD

**Issue by hoijui** [vanilla-extracts/calc#36]
Wow.. thank you.. I expected something much more "mini" with that name.. impressive; and yet it has few deps and compiles in 30s on my moderate machine; great!

So .. maybe you are not interested in that at all, but ... I found this through a search on crates.io for "calc", looking for a simple CLI calculator. For me personally, it would be cool if some of these non-interactive use cases would be supported:

```shell
mini-calc 1 + 3
mini-calc 1+3
mini-calc "1 + 3"
echo "1 + 3" | mini-calc
mini-calc -h
mini-calc --help
```

There is no urgent need for this on my side, just wanted to put it out here.

**Comment by vanilla-extracts** [comment]
Hey! That's great hearing from an actual user lol! 
It's something I haven't thought of doing but it could be useful, to be honest this calc was built for education purposes only and to learn the language so yeah I'll look into that :)

Thank you for your post and for enjoying my pet project :+1:

**Comment by hoijui** [comment]
:-)
for me, a fast CLI calculator still has its place in todays world.
thank you for this!

**Comment by vanilla-extracts** [comment]
Done!
(just not the echo one)

**Comment by hoijui** [comment]
Thank you!! :-)
perfect! I tried it, and set it as my primary one!

**Comment by vanilla-extracts** [comment]
A little late to the party but piping was added at version 2.12.3 :)
