### ISSUE TITLE
feat request: Repl syntax highlighting

### ISSUE THREAD

**Issue by leana8959** [vanilla-extracts/calc#52]
Hello,

I think it would be nice to have repl syntax highlighting. Here's an example of how it's implemented in `amm` (a Scala interpreter)
![image](https://github.com/user-attachments/assets/c93765aa-aa3d-41f0-a37d-cb82c7434549)

I think to improve the readability, we could even consider having a colorscheme where each type of literal has its own color.

Thanks and have a nice day :)

**Comment by vanilla-extracts** [comment]
I'll be working on it when I have time, thanks :+1:

**Comment by vanilla-extracts** [comment]
Is that like what you thought?
![image](https://github.com/user-attachments/assets/bd57b813-f258-4800-8ba8-a2b0ad28e6cd)

**Comment by leana8959** [comment]
Beautiful! Thank you✨

**Comment by vanilla-extracts** [comment]
Just did my duty 🫡🫡
Now I need to figure out how to colour the text we're editing 🤔

Is that even possible in cli ? I think so

EDIT: Dropped the syntax highlighting in the CLI
